# Generated by Django 5.0.6 on 2024-06-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_photo'),
        ('users', '0005_remove_post_user_profile_post_user_alter_post_text_and_more'),
    ]

    operations = [
    ]
