# Generated by Django 4.2.6 on 2023-10-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_city_travelplaces_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('story', models.TextField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='places_ph')),
            ],
        ),
        migrations.AddField(
            model_name='travelplaces',
            name='tourSites',
            field=models.ManyToManyField(to='api.touristsites'),
        ),
    ]
