# Generated by Django 4.2.6 on 2023-10-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hotels_tickets_airlines_travelplaces_airlines_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirLines',
            new_name='AirLine',
        ),
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='TouristSites',
            new_name='TouristSite',
        ),
        migrations.RenameModel(
            old_name='TravelPlaces',
            new_name='TravelPlace',
        ),
    ]
