# Generated by Django 5.0.1 on 2024-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_travelplace_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
