# Generated by Django 5.0.1 on 2024-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_travelplaceimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='photos',
            field=models.ManyToManyField(to='api.travelplaceimages'),
        ),
    ]
