# Generated by Django 5.0.1 on 2024-06-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='H_photo',
        ),
        migrations.AddField(
            model_name='resturant',
            name='R_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resturants_ph'),
        ),
    ]
