# Generated by Django 5.0.1 on 2024-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_resturant_h_photo_resturant_r_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='resturants',
            field=models.ManyToManyField(to='api.resturant'),
        ),
    ]
