# Generated by Django 5.0.1 on 2024-06-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_hotelimages_hotel_address_hotel_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
