# Generated by Django 5.0.1 on 2024-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='h_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
