# Generated by Django 5.0.1 on 2024-06-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_travelplace_average_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
