# Generated by Django 5.0.1 on 2024-07-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirLine',
            new_name='Agencys',
        ),
        migrations.RenameField(
            model_name='travelplace',
            old_name='airlines',
            new_name='agencys',
        ),
    ]
