# Generated by Django 5.0.1 on 2024-07-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_ticket_date_ticket_destenation_alter_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencys',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='agency',
            field=models.ManyToManyField(to='api.agencys'),
        ),
    ]
