# Generated by Django 5.0.1 on 2024-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='image_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
