# Generated by Django 5.0.1 on 2024-08-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_travelplace_image_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplace',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='travelplace',
            name='date',
        ),
        migrations.RemoveField(
            model_name='travelplace',
            name='price',
        ),
        migrations.RemoveField(
            model_name='travelplace',
            name='tourSites',
        ),
    ]
