# Generated by Django 5.0.1 on 2024-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_ticket_t_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplaceimages',
            name='image_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
